version: '3.1'

services:
  arbitrum-goerli-fullnode:
    image: 'offchainlabs/nitro-node:v2.0.14-2baa834'
    restart: always
    stop_grace_period: 30s
    user: root
    volumes:
      - 'arbitrum-goerli-fullnode:/arbitrum-node'
    expose:
      - 8547
      - 8548
    command:
      - --init.url=https://snapshot.arbitrum.foundation/goerli/nitro-pruned.tar
      - --persistent.chain=/arbitrum-node/data/
      - --persistent.global-config=/arbitrum-node/
      - --l1.url=${ARBITRUM_GOERLI_L1_URL}
      - --l2.chain-id=421613
      - --http.api=net,web3,eth,debug 
      - --http.corsdomain=* 
      - --http.addr=0.0.0.0 
      - --http.vhosts=*
      - --ws.port=8547
      - --ws.addr=0.0.0.0
      - --ws.origins=*
    restart: unless-stopped                 
    labels:                     
      - "traefik.enable=true"
      - "traefik.http.middlewares.arbitrum-goerli-stripprefix.stripprefix.prefixes=/arbitrum-goerli"                      
      - "traefik.http.services.arbitrum-goerli.loadbalancer.server.port=8547"
      - "traefik.http.routers.arbitrum-goerli.entrypoints=websecure"                                              
      - "traefik.http.routers.arbitrum-goerli.tls.certresolver=myresolver"                                        
      - "traefik.http.routers.arbitrum-goerli.rule=Host(`$DOMAIN`) && PathPrefix(`/arbitrum-goerli`)"                     
      - "traefik.http.routers.arbitrum-goerli.middlewares=arbitrum-goerli-stripprefix, ipwhitelist"                           
    networks:                                                                                         
      - chains

volumes:  
    arbitrum-goerli-fullnode:
