version: "3.1"
services:
  arbitrum-proxy:
    image: stakesquid/eth-cluster@sha256:be8ac9d1325b7389a6cb8d57fe00a1cc55ed47a6a48861e93e326453676e56d6
    environment:
      - FULLNODE_WS_URL=${ARBITRUM_PROXY_FULLNODE_WS}
      - FULLNODE_RPC_URL=${ARBITRUM_PROXY_FULLNODE_RPC}
      - ARCHIVE_RPC_URL=${ARBITRUM_PROXY_ARCHIVE_RPC}
      - ALL_TRACE_TO_ARCHIVE=${ARBITRUM_PROXY_TRACE_TO_ARCHIVE:-true}
    expose:
      - "8545"
    networks:
      - chains
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.arbitrum-proxy-stripprefix.stripprefix.prefixes=$ARBITRUM_PROXY_PREFIX"
      - "traefik.http.services.arbitrum-proxy.loadbalancer.server.port=8545"
      - "traefik.http.routers.arbitrum-proxy.entrypoints=websecure"
      - "traefik.http.routers.arbitrum-proxy.tls.certresolver=myresolver"
      - "traefik.http.routers.arbitrum-proxy.rule=Host(`$ARBITRUM_PROXY_DOMAIN`) && PathPrefix(`$ARBITRUM_PROXY_PREFIX`)"
      - "traefik.http.routers.arbitrum-proxy.middlewares=arbitrum-proxy-stripprefix, ipwhitelist"
