version: '3.1'

services:
  bsc-erigon:
    image: stakesquid/bsc-erigon
    user: root
    volumes:
      - "bsc-erigon:/datadir"
      - "/slowdisk:/slowdisk"
    ports:
      - "54993:54993"
      - "54993:54993/udp"
      - "25703:25703"
      - "25703:25703/udp"
    restart: unless-stopped
    command: --db.pagesize=16k --chain=bsc --prune=hrtc --sentry.drop-useless-peers --http --http.addr=0.0.0.0 --http.port=8545 --http.compression --http.vhosts='*' --http.corsdomain='*' --http.api=eth,debug,net,web3,erigon --ws --ws.compression --rpc.gascap=300000000 --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --bodies.cache=5G --rpc.batch.limit=200000 --batchSize=2048MB --port=54993 --p2p.protocol=66 --datadir=/datadir --ethash.dagdir=/datadir/ethash --rpc.returndata.limit=1100000 --torrent.port=25703 --torrent.download.rate=80mb

    stop_grace_period: 1m
    labels:
      - "prometheus-scrape.enabled=true"
      - "prometheus-scrape.port=6060"
      - "prometheus-scrape.job_name=erigon"
      - "prometheus-scrape.metrics_path=/debug/metrics/prometheus"
      - "traefik.enable=true"
      - "traefik.http.middlewares.bsc-erigon-stripprefix.stripprefix.prefixes=/bsc-erigon"
      - "traefik.http.services.bsc-erigon.loadbalancer.server.port=8545"
      - "traefik.http.routers.bsc-erigon.entrypoints=websecure"
      - "traefik.http.routers.bsc-erigon.tls.certresolver=myresolver"
      - "traefik.http.routers.bsc-erigon.rule=Host(`$DOMAIN`) && PathPrefix(`/bsc-erigon`)"
      - "traefik.http.routers.bsc-erigon.middlewares=bsc-erigon-stripprefix, ipwhitelist"
    networks:
      - chains

volumes:
    bsc-erigon:
