version: '3.1'

services:

  bsc-testnet:                                                                                                                                                            
    image: ghcr.io/bnb-chain/bsc:1.4.15
    user: root
    ports:
      - "29061:29061"
      - "29061:29061/udp"
    expose:                                                                              
      - "8545"                                                                           
      - "8546"                                                                           
      - "29061"                                                                          
    volumes:                                                                             
      - bsc-testnet:/bsc-testnet/.ethereum                                                                                                                                                
      - ./bsc-testnet/config:/bsc-testnet/config
    entrypoint: geth
    command: --config=/bsc-testnet/config/config.toml --ws.origins='*' --history.transactions=0 --state.scheme=path --syncmode=full --db.engine=pebble --rpc.gascap=600000000
    restart: unless-stopped
    stop_grace_period: 3m
    networks: 
      - chains
    labels:                                                                              
      - "traefik.enable=true"                                                            
      - "traefik.http.middlewares.bsc-testnet-stripprefix.stripprefix.prefixes=/bsc-testnet"             
      - "traefik.http.services.bsc-testnet.loadbalancer.server.port=8545"                        
      - "traefik.http.routers.bsc-testnet.entrypoints=websecure"                                 
      - "traefik.http.routers.bsc-testnet.tls.certresolver=myresolver"                           
      - "traefik.http.routers.bsc-testnet.rule=Host(`$DOMAIN`) && PathPrefix(`/bsc-testnet`)"            
      - "traefik.http.routers.bsc-testnet.middlewares=bsc-testnet-stripprefix, ipwhitelist"

volumes:
    bsc-testnet:

