version: '3.1'

services:

  bsc:                                                                                                                                                            
    image: ghcr.io/bnb-chain/bsc:1.3.12
    user: root
    ports:
      - "29061:29061"
      - "29061:29061/udp"
    expose:                                                                              
      - "8545"                                                                           
      - "8546"                                                                           
      - "29061"                                                                          
    volumes:                                                                             
      - bsc:/bsc/node                                                                                                                                                
      - ./bsc/config:/bsc/config                                               
    command: "--port=29061 --history.transactions=0 --syncmode=full --db.engine=pebble --state.scheme=path --http.addr 0.0.0.0 --http.port 8545 --http.vhosts '*' --verbosity 5 --ws.addr 0.0.0.0 --ws.port 8545 --ws.origins '*' --datadir /bsc/node --config /bsc/config/config.toml"
    restart: unless-stopped
    stop_grace_period: 3m
    networks: 
      - chains
    labels:                                                                              
      - "traefik.enable=true"                                                            
      - "traefik.http.middlewares.bsc-stripprefix.stripprefix.prefixes=/bsc"             
      - "traefik.http.services.bsc.loadbalancer.server.port=8545"                        
      - "traefik.http.routers.bsc.entrypoints=websecure"                                 
      - "traefik.http.routers.bsc.tls.certresolver=myresolver"                           
      - "traefik.http.routers.bsc.rule=Host(`$DOMAIN`) && PathPrefix(`/bsc`)"            
      - "traefik.http.routers.bsc.middlewares=bsc-stripprefix, ipwhitelist"

volumes:
    bsc:

