version: '3.1'

services:

  bsc:                                                                                                                                                            
    image: ghcr.io/bnb-chain/bsc:1.3.12
    user: root
    ports:
      - "29061:29061"
      - "29061:29061/udp"
    expose:                                                                              
      - "8545"                                                                           
      - "8546"                                                                           
      - "29061"                                                                          
    volumes:                                                                             
      - bsc:/bsc/node                                                                                                                                                
      - ./bsc/config:/bsc/config
    environment:
      GETH_HTTP_ADDR: 0.0.0.0
      GETH_HTTP: 'true'
      GETH_HTTP_PORT: 8545
      GETH_HTTP_VHOSTS: '*'
      GETH_WS: 'true'
      GETH_WS_ADDR: 0.0.0.0
      GETH_WS_PORT: 8545
      GETH_WS_ORIGINS: '*'
      GETH_DISCOVERY_PORT: 29061
      GETH_PORT: 29061
      GETH_DATADIR: /bsc/node
      GETH_STATE_SCHEME: path
      GETH_DB_ENGINE: pebble
      GETH_SYNCMODE: full
      GETH_HISTORY_TRANSACTIONS: 0
    restart: unless-stopped
    stop_grace_period: 3m
    networks: 
      - chains
    labels:                                                                              
      - "traefik.enable=true"                                                            
      - "traefik.http.middlewares.bsc-stripprefix.stripprefix.prefixes=/bsc"             
      - "traefik.http.services.bsc.loadbalancer.server.port=8545"                        
      - "traefik.http.routers.bsc.entrypoints=websecure"                                 
      - "traefik.http.routers.bsc.tls.certresolver=myresolver"                           
      - "traefik.http.routers.bsc.rule=Host(`$DOMAIN`) && PathPrefix(`/bsc`)"            
      - "traefik.http.routers.bsc.middlewares=bsc-stripprefix, ipwhitelist"

volumes:
    bsc:

