version: "3.1"
services:
  celo-proxy:
    image: stakesquid/eth-cluster@sha256:537f9207d3894732c946244b464c4482fb0661f2b3ac1daffb1f549a64a49d79
    environment:
      - FULLNODE_WS_URL=${CELO_PROXY_FULLNODE_WS}
      - FULLNODE_RPC_URL=${CELO_PROXY_FULLNODE_RPC}
      - ARCHIVE_RPC_URL=${CELO_PROXY_ARCHIVE_RPC}
    expose:
      - "8545"
    networks:
      - chains
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.celo-proxy-stripprefix.stripprefix.prefixes=$CELO_PROXY_PREFIX"
      - "traefik.http.services.celo-proxy.loadbalancer.server.port=8545"
      - "traefik.http.routers.celo-proxy.entrypoints=websecure"
      - "traefik.http.routers.celo-proxy.tls.certresolver=myresolver"
      - "traefik.http.routers.celo-proxy.rule=Host(`$CELO_PROXY_DOMAIN`) && PathPrefix(`$CELO_PROXY_PREFIX`)"
      - "traefik.http.routers.celo-proxy.middlewares=celo-proxy-stripprefix, ipwhitelist"
