version: '3.1'

services:

### NODES
  geth-goerli:
    image: ethereum/client-go:latest
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - geth-goerli:/.goerli
    command: "--goerli --http --http.api eth,net --http.addr 0.0.0.0 --http.port 8545 --http.vhosts=* --syncmode full --datadir .goerli --verbosity 3"
    networks:
      - $NET_POKT

  geth-rinkeby:
    image: ethereum/client-go:latest
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - geth-rinkeby:/.rinkeby
    command: "--rinkeby --http --http.api eth,net --http.addr 0.0.0.0 --http.port 8545 --http.vhosts=* --syncmode full --datadir .rinkeby --verbosity 3"
    networks:
      - $NET_POKT
    restart: unless-stopped

  geth-ropsten:
    image: ethereum/client-go:latest
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - geth-ropsten:/.ropsten
    command: "--ropsten --http --http.api eth,net --http.addr 0.0.0.0 --http.port 8545 --http.vhosts=* --syncmode full --datadir .ropsten --verbosity 3"
    networks:
      - $NET_POKT
    restart: unless-stopped

  geth-mainnet:
    image: ethereum/client-go:latest
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - geth-mainnet:/.mainnet
    command: "--http  --http.api eth,net --http.addr 0.0.0.0 --http.port 8545 --http.vhosts=* --syncmode full --datadir .mainnet --verbosity 3"
    networks:
      - $NET_POKT
    restart: unless-stopped

  erigon-trace:
    image: thorax/erigon
    expose:
    - "30303"
    - "30304"
    volumes:
      - erigon-trace:/home/erigon/.local/share/erigon
    command: erigon --chain mainnet --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --private.api.addr=0.0.0.0:9090 --pprof --pprof.addr=0.0.0.0 --pprof.port=6061
    networks:
      - $NET_POKT
    restart: unless-stopped

  rpcdaemon:
    image: thorax/erigon:latest
    command: rpcdaemon --datadir=/home/erigon/.local/share/erigon --private.api.addr=erigon:9090 --txpool.api.addr=erigon:9090 --http.addr=0.0.0.0 --http.vhosts=* --http.corsdomain=* --http.api=eth,debug,net,trace --ws
    pid: service:erigon-trace # Use erigon's PID namespace. It's required to open Erigon's DB from another process (RPCDaemon local-mode)
    volumes:
      - erigon-trace:/home/erigon/.local/share/erigon
    expose:
      - "8545"
    restart: unless-stopped
    depends_on:
      - "erigon-trace"
    networks:
      - $NET_POKT

  avalanche:
    image: avaplatform/avalanchego
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - avalanche:/root/.avalanche
    command: "/avalanchego/build/avalanchego --http-host="
    networks:
      - $NET_POKT
    restart: unless-stopped


### VOLUMES

volumes:
  geth-goerli:
  geth-rinkeby:
  geth-ropsten:
  geth-mainnet:
  erigon-trace:
  avalanche:
