version: '3.1'

services:

  #geth-rinkeby:
  #  image: ethereum/client-go:v1.9.13
  #  expose:
  #    - "8545"
  #    - "8546"
  #    - "30303"
  #  volumes:
  #    - geth-rinkeby:/.rinkeby
  #  command: "--rinkeby --rpc --rpcapi eth,net --rpcaddr 0.0.0.0 --rpcport 8545 --rpcvhosts=* --syncmode fast --datadir .rinkeby --verbosity 3"
  #  networks:
  #    - pocket

  #geth-mainnet:
  #  image: ethereum/client-go:v1.9.13
  #  expose:
  #    - "8545"
  #    - "8546"
  #    - "30303"
  #  volumes:
  #    - geth-mainnet:/.mainnet
  #  command: "--rpc  --rpcapi eth,net --rpcaddr 0.0.0.0 --rpcport 8545 --rpcvhosts=* --syncmode fast --datadir .mainnet --verbosity 3"
  #  networks:
  #    - pocket

  pocket-fullnode:
    image: poktnetwork/pocket-core:stagenet-latest
    ports:
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:26656:26656"
    expose:
      - 26656
      - 8081
    command: pocket start --seeds=$POCKET_TEST_SEEDS --testnet
    environment:
      - POCKET_CORE_KEY=$POCKET_CORE_KEY
      - POCKET_CORE_PASSPHRASE=$POCKET_CORE_PASSPHRASE
    volumes:
      - ./chains/chains.json:/home/app/.pocket/config/chains.json
      - pocket-data:/home/app/.pocket
    networks:
      - pocket

volumes:
#  geth-mainnet:
#  geth-rinkeby:
  pocket-data:


networks:
  pocket:
    driver: bridge