version: '3.1'

services:

  binance-smart-chain:                                                                                                                                                            
    image: dysnix/bsc                                                                    
    expose:                                                                              
      - "8545"                                                                           
      - "8546"                                                                           
      - "30303"                                                                          
    volumes:                                                                             
      - /root/bsc-datadir/server1/data-seed:/datadir                                                                                                                                                
      - /root/bsc-config/config.toml:/config.toml                                               
    command: "--cache 18000 --rpc --rpcaddr=\"0.0.0.0\" --rpc.allow-unprotected-txs --txlookuplimit 0 --syncmode snap --config /config.toml --datadir /datadir"
    restart: unless-stopped                                                              
    networks: 
      - chains
    labels:                                                                              
      - "traefik.enable=true"                                                            
      - "traefik.http.middlewares.ipwhitelist.ipwhitelist.sourcerange=$WHITELIST"        
      - "traefik.http.middlewares.bsc-stripprefix.stripprefix.prefixes=/bsc"             
      - "traefik.http.services.bsc.loadbalancer.server.port=8545"                        
      - "traefik.http.routers.bsc.entrypoints=websecure"                                 
      - "traefik.http.routers.bsc.tls.certresolver=myresolver"                           
      - "traefik.http.routers.bsc.rule=Host(`$DOMAIN`) && PathPrefix(`/bsc`)"            
      - "traefik.http.routers.bsc.middlewares=avalanche-stripprefix, ipwhitelist" 



