version: '3.1'

services:

  haproxy:
    image: haproxytech/haproxy-alpine:latest
    ports:
      - "80:80"
    expose:
      - 80
    environment:
      - AUTH_HTTP=$AUTH_HTTP
    volumes:
      - ./haproxy/:/usr/local/etc/haproxy:ro
    networks:
      - $NET_POKT
    restart: unless-stopped


