version: '3.1'

services:

  geth-kovan:
    image: parity/parity:latest
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - geth-kovan:/.kovan
    command: "--kovan"
    networks:
      - pocket

  geth-goerli:
    image: ethereum/client-go:latest
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - geth-goerli:/.goerli
    command: "--goerli --http --http.api eth,net --http.addr 0.0.0.0 --http.port 8545 --http.vhosts=* --syncmode fast --datadir .goerli --verbosity 3"
    networks:
      - pocket

  geth-rinkeby:
    image: ethereum/client-go:latest
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - geth-rinkeby:/.rinkeby
    command: "--rinkeby --http --http.api eth,net --http.addr 0.0.0.0 --http.port 8545 --http.vhosts=* --syncmode fast --datadir .rinkeby --verbosity 3"
    networks:
      - pocket

  geth-mainnet:
    image: ethereum/client-go:latest
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - geth-mainnet:/.mainnet
    command: "--http  --http.api eth,net --http.addr 0.0.0.0 --http.port 8545 --http.vhosts=* --syncmode full --datadir .mainnet --verbosity 3"
    networks:
      - pocket

  pocket-fullnode:
    image: poktnetwork/pocket-core:stagenet-latest
    ports:
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:26656:26656"
    expose:
      - 26656
      - 8081
    command: pocket start --seeds=$POCKET_TEST_SEEDS --testnet
    environment:
      - POCKET_CORE_KEY=$POCKET_CORE_KEY
      - POCKET_CORE_PASSPHRASE=$POCKET_CORE_PASSPHRASE
    volumes:
      - ./chains/chains.json:/home/app/.pocket/config/chains.json
      - pocket-data:/home/app/.pocket
    networks:
      - pocket

volumes:
  geth-kovan:
  geth-goerli:
  geth-rinkeby:
  geth-mainnet:
  pocket-data:


networks:
  pocket:
    driver: bridge