version: '3.1'

services:
  haproxy:
    image: haproxytech/haproxy-alpine:latest
    ports:
      - "80:80"
    expose:
      - 80
    environment:
      - AUTH_HTTP=$AUTH_HTTP
      - MAINNODE=$MAIN_NODE
    volumes:
      - ./haproxy/:/usr/local/etc/haproxy:ro
    restart: unless-stopped