version: '3.1'

services:

  pocket-testnet:
    image: poktnetwork/pocket-core:stagenet-latest
    ports:
      - "127.0.0.1:8082:8081"
      - "127.0.0.1:26657:26656"
    expose:
      - 26656
      - 8081
    command:  pocket start --seeds=$POCKET_TEST_SEEDS --testnet
    #command: pocket start --simulateRelay
    environment:
      - POCKET_CORE_KEY=$POCKET_CORE_KEY_TEST
      - POCKET_CORE_PASSPHRASE=$POCKET_CORE_PASSPHRASE_TEST
    volumes:
      - ./chains/chains_testnet.json:/home/app/.pocket/config/chains.json
      - pocket-testnet:/home/app/.pocket
    networks:
      - $NET_POKT
    restart: unless-stopped

### VOLUMES

volumes:
  pocket-testnet:


