version: '3.1'

services:
  dshackle:
    image: drpcorg/dshackle:0.51.0
    restart: unless-stopped
    volumes:
      - ./main_configs:/etc/dshackle
    expose:
      - 8080
      - 25703
    ports:
#      - "8080:8080"
#      - "8081:8081"
#      - "8082:8082"
      - "2449:2449"
#      - "25703:25703"
    labels:
      - "prometheus-scrape.enabled=true"
      - "prometheus-scrape.port=8081"
      - "prometheus-scrape.job_name=drpc-dshackle"
      - "prometheus-scrape.metrics_path=/metrics"
      - "traefik.enable=true"
      #- "traefik.http.middlewares.public-stripprefix.stripprefix.prefixes=/public"
      #- "traefik.http.services.public.loadbalancer.server.port=25703"
      #- "traefik.http.routers.public.entrypoints=websecure"
      #- "traefik.http.routers.public.tls.certresolver=myresolver"
      #- "traefik.http.routers.public.rule=Host(`$GWDOMAIN`) && PathPrefix(`/public`)"
      #- "traefik.http.routers.public.middlewares=public-stripprefix"
      - "traefik.http.services.drpc.loadbalancer.server.scheme=h2c"
      - "traefik.http.services.drpc.loadbalancer.server.port=2449"
      - "traefik.http.routers.drpc.entrypoints=grpc"
      - "traefik.http.routers.drpc.tls.certresolver=myresolver"
      - "traefik.http.routers.drpc.rule=Host(`$GWDOMAIN`)"


    networks:
      - chains
    logging: 
      driver: journald
      
  redis:
    image: healthcheck/redis:alpine
    restart: unless-stopped
    command:
      - "redis-server"
      - "--maxmemory ${REDIS_RAM}"
      - "--maxmemory-policy allkeys-lru"
      - '--save ""'
    networks:
      - chains

