version: '3.1'

services:

  dshackle:
    container_name: dshackle
    image: emeraldpay/dshackle:0.13.1
    restart: unless-stopped
    volumes:
      - ./dshackle/config:/etc/dshackle # This should hold all your yaml files
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    environment:
      - ALCHEMY_KEY=${ALCHEMY_KEY}
      - ANYBLOCK_KEY=${ANYBLOCK_KEY}
      - CHAINSTACK_NODE=${CHAINSTACK_NODE}
      - CHAINSTACK_USERNAME=${CHAINSTACK_USERNAME}
      - CHAINSTACK_PASSWORD=${CHAINSTACK_PASSWORD}
      - COINBASE_USERNAME=${COINBASE_USERNAME}
      - COINBASE_PASSWORD=${COINBASE_PASSWORD}
      - INFURA_KEY=${INFURA_KEY}
      - RIVET_KEY=${RIVET_KEY}
      - QUICKNODE_HTTP=${QUICKNODE_HTTP}
      - QUICKNODE_WSS=${QUICKNODE_WSS}

    redis:
      container_name: redis
      image: healthcheck/redis:alpine
      restart: unless-stopped
      environment:
        - REDIS_RAM=${REDIS_RAM}
      command:
        - "redis-server"
        - "--maxmemory ${REDIS_RAM}"
        - "--maxmemory-policy allkeys-lru"
        - '--save ""'



