version: '3.1'

services:
  erigon-bsc-fullnode:
    image: chainstack/bsc-erigon:1.1.8
    user: root
    volumes:
      - "bsc-erigon-fullnode:/datadir"
    ports:
      - "38554:38554"
      - "38554:38554/udp"
    restart: unless-stopped
    command: erigon --chain=bsc --prune=hrtc --sentry.drop-useless-peers --http --http.addr=0.0.0.0 --http.port=8545 --http.compression --http.vhosts='*' --http.corsdomain='*' --http.api=eth,debug,net,web3,erigon --ws --ws.compression --rpc.gascap=300000000 --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --bodies.cache=5G --rpc.batch.limit=200000 --batchSize=2048MB --port=38554 --p2p.protocol=66 --datadir=/datadir --ethash.dagdir=/datadir/ethash --rpc.returndata.limit=1100000

    stop_grace_period: 1m
    labels:
      - "prometheus-scrape.enabled=true"
      - "prometheus-scrape.port=6060"
      - "prometheus-scrape.job_name=erigon"
      - "prometheus-scrape.metrics_path=/debug/metrics/prometheus"
      - "traefik.enable=true"
      - "traefik.http.middlewares.erigon-bsc-fullnode-stripprefix.stripprefix.prefixes=/bsc"
      - "traefik.http.services.erigon-bsc-fullnode.loadbalancer.server.port=8545"
      - "traefik.http.routers.erigon-bsc-fullnode.entrypoints=websecure"
      - "traefik.http.routers.erigon-bsc-fullnode.tls.certresolver=myresolver"
      - "traefik.http.routers.erigon-bsc-fullnode.rule=Host(`$DOMAIN`) && PathPrefix(`/bsc`)"
      - "traefik.http.routers.erigon-bsc-fullnode.middlewares=erigon-bsc-fullnode-stripprefix, ipwhitelist"
    networks:
      - chains

volumes:
    bsc-erigon-fullnode:
