version: '3.1'

services:
  erigon-polygon:
    build:
      args:
        ERIGON_VERSION: v0.0.3
      context: ./polygon/erigon
      dockerfile: Dockerfile
    environment:
      - SNAPSHOT_URL=https://matic-blockchain-snapshots.s3-accelerate.amazonaws.com/matic-mainnet/erigon-archive-snapshot-2022-10-12.tar.gz
      - BOOTSTRAP=1
    volumes:
      - "bor-archive_data:/datadir"
    ports:
      - "40303:40303"
      - "40303:40303/udp"
    depends_on:
      - heimdallr
    restart: unless-stopped
    stop_grace_period: 1m
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.bor-stripprefix.stripprefix.prefixes=/polygon-archive"
      - "traefik.http.services.bor.loadbalancer.server.port=8545"
      - "traefik.http.routers.bor.entrypoints=websecure"
      - "traefik.http.routers.bor.tls.certresolver=myresolver"
      - "traefik.http.routers.bor.rule=Host(`$DOMAIN`) && PathPrefix(`/polygon-archive`)"
      - "traefik.http.routers.bor.middlewares=bor-stripprefix, ipwhitelist"
    networks:
      - chains

volumes:
    bor-archive_data:
