version: '3.1'

services:
  erigon-polygon:
    image: thorax/erigon:v2.31.0
    environment:
      - SNAPSHOT_URL=https://matic-blockchain-snapshots.s3-accelerate.amazonaws.com/matic-mainnet/erigon-archive-snapshot-2022-12-06.tar.gz
      - BOOTSTRAP=1
      - HEIMDALL_RPC=https://heimdall.stakesystems.io
    volumes:
      - "polygon-archive_data:/datadir"
    ports:
      - "40303:40303"
      - "40303:40303/udp"
    restart: unless-stopped
    stop_grace_period: 1m
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.erigon-polygon-stripprefix.stripprefix.prefixes=/polygon-archive"
      - "traefik.http.services.erigon-polygon.loadbalancer.server.port=8545"
      - "traefik.http.routers.erigon-polygon.entrypoints=websecure"
      - "traefik.http.routers.erigon-polygon.tls.certresolver=myresolver"
      - "traefik.http.routers.erigon-polygon.rule=Host(`$DOMAIN`) && PathPrefix(`/polygon-archive`)"
      - "traefik.http.routers.erigon-polygon.middlewares=erigon-polygon-stripprefix, ipwhitelist"
    networks:
      - chains

volumes:
    polygon-archive_data:
