version: '3.1'

services:
  erigon-holesky:
    image: thorax/erigon:v2.60.0
    user: root
    expose:
      - "16630"
      - "9090"
      - "8545"
      - "8551"
    ports:
      - "15432:15432"
      - "15432:15432/udp"
    volumes:
      - erigon-holesky:/root/.local/share/erigon
      - /slowdisk:/slowdisk
      - .jwtsecret:/jwtsecret
    networks:
      - chains
    command: >
      --chain holesky
      --internalcl
      --caplin.archive
      --caplin.backfilling
      --caplin.backfilling.blob
      --caplin.backfilling.blob.no-pruning
      --port=15432
      --metrics --metrics.addr=0.0.0.0 --metrics.port=6060
      --private.api.addr=0.0.0.0:9090
      --torrent.upload.rate="1250mb"
      --torrent.download.rate="1250mb"
      --nat=stun
      --pprof
      --pprof.addr=0.0.0.0
      --pprof.port=6061
      --authrpc.addr=0.0.0.0
      --authrpc.vhosts=*
      --authrpc.jwtsecret=/jwtsecret
      --http.addr=0.0.0.0
      --http.vhosts=*
      --http.corsdomain=*
      --http.api=eth,erigon,web3,net,debug,trace,txpool
      --beacon.api=beacon,builder,config,debug,node,validator,lighthouse
      --rpc.returndata.limit=1100000
      --rpc.gascap=5000000000
      --ws 
    restart: unless-stopped
    stop_grace_period: 1m
    labels:
      - "prometheus-scrape.enabled=true"
      - "prometheus-scrape.port=6060"
      - "prometheus-scrape.job_name=erigon"
      - "prometheus-scrape.metrics_path=/debug/metrics/prometheus"
      - "traefik.enable=true"
      - "traefik.http.middlewares.erigon-holesky-stripprefix.stripprefix.prefixes=/holesky-erigon"
      - "traefik.http.services.erigon-holesky.loadbalancer.server.port=8545"
      - "traefik.http.routers.erigon-holesky.entrypoints=websecure"
      - "traefik.http.routers.erigon-holesky.tls.certresolver=myresolver"
      - "traefik.http.routers.erigon-holesky.rule=Host(`$DOMAIN`) && PathPrefix(`/holesky-erigon`)"
      - "traefik.http.routers.erigon-holesky.middlewares=erigon-holesky-stripprefix, ipwhitelist"
      
volumes:
    erigon-holesky:

