version: '3.1'

services:
  erigon-polygon:
    image: thorax/erigon:v2.31.0
    volumes:
      - "polygon-archive_data:/datadir"
    ports:
      - "40303:40303"
      - "40303:40303/udp"
    restart: unless-stopped
    command: >
      erigon
      --chain=bor-mainnet \
      --bor.heimdall=https://heimdall.stakesystems.io \
      --datadir=${ERIGON_HOME} \
      --http --http.addr="0.0.0.0" --http.port="8545" --http.compression --http.vhosts="*" --http.corsdomain="*" --http.api="eth,debug,net,trace,web3,erigon,bor" \
      --ws --ws.compression \
      --snap.keepblocks=true \
      --snapshots="true" \
      --torrent.upload.rate="1250mb" --torrent.download.rate="1250mb" \
      --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 \
      --pprof --pprof.addr=0.0.0.0 --pprof.port=6061
    stop_grace_period: 1m
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.erigon-polygon-stripprefix.stripprefix.prefixes=/polygon-archive"
      - "traefik.http.services.erigon-polygon.loadbalancer.server.port=8545"
      - "traefik.http.routers.erigon-polygon.entrypoints=websecure"
      - "traefik.http.routers.erigon-polygon.tls.certresolver=myresolver"
      - "traefik.http.routers.erigon-polygon.rule=Host(`$DOMAIN`) && PathPrefix(`/polygon-archive`)"
      - "traefik.http.routers.erigon-polygon.middlewares=erigon-polygon-stripprefix, ipwhitelist"
    networks:
      - chains

volumes:
    polygon-archive_data:
