version: '3.1'

services:
  erigon-polygon:
    image: thorax/erigon:v2.54.0
    user: root
    volumes:
      - "polygon-archive_data:/datadir"
    ports:
      - "61044:61044"
      - "61044:61044/udp"
      - "21827:21827"
      - "21827:21827/udp"
      - "14745:14745"
      - "14745:14745/udp"
      - "63195:63195"
      - "63195:63195/udp"
    restart: unless-stopped
#    command: --chain bor-mainnet --snapshots false --datadir /datadir --ethash.dagdir /datadir/ethash --snap.stop --bor.heimdall https://heimdall.stakesystems.io --http --http.addr 0.0.0.0 --http.port 8545 --http.compression --http.vhosts * --http.corsdomain * --http.api eth,debug,net,trace,web3,erigon,bor --ws --ws.compression --rpc.gascap 300000000 --metrics --metrics.addr 0.0.0.0 --metrics.port 6060 --bodies.cache 5G --rpc.batch.limit 200000 --db.pagesize 16k --batchSize 2048MB --port 61044 --p2p.protocol 66
    command: --chain=bor-mainnet --nat=stun --snapshots=false --snap.stop --bor.heimdall=https://heimdall.stakesystems.io --http --http.addr=0.0.0.0 --http.port=8545 --http.compression --http.vhosts='*' --http.corsdomain='*' --http.api=eth,debug,net,trace,web3,erigon,bor --ws --ws.compression --rpc.gascap=300000000 --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --bodies.cache=5G --rpc.batch.limit=200000 --db.pagesize=16k --batchSize=2048MB --port=61044 --p2p.protocol=66 --p2p.allowed-ports 63195 --p2p.allowed-ports 14745 --p2p.allowed-ports 21827 --datadir=/datadir --ethash.dagdir=/datadir/ethash --rpc.returndata.limit=1100000 --db.size.limit=12t
    stop_grace_period: 1m
    labels:
      - "prometheus-scrape.enabled=true"
      - "prometheus-scrape.port=6060"
      - "prometheus-scrape.job_name=erigon"
      - "prometheus-scrape.metrics_path=/debug/metrics/prometheus"
      - "traefik.enable=true"
      - "traefik.http.middlewares.erigon-polygon-stripprefix.stripprefix.prefixes=/polygon-archive"
      - "traefik.http.services.erigon-polygon.loadbalancer.server.port=8545"
      - "traefik.http.routers.erigon-polygon.entrypoints=websecure"
      - "traefik.http.routers.erigon-polygon.tls.certresolver=myresolver"
      - "traefik.http.routers.erigon-polygon.rule=Host(`$DOMAIN`) && PathPrefix(`/polygon-archive`)"
      - "traefik.http.routers.erigon-polygon.middlewares=erigon-polygon-stripprefix, ipwhitelist"
    networks:
      - chains

volumes:
    polygon-archive_data:
