version: '3.1'

services:
  evmos:
    image: tharsishq/evmos:v2.0.1
    expose:
      - "8545"
    ports:
      - "26657:26657"
      - "26656:26656"      
    volumes:
      - evmos_data:/root/.evmosd
    command: "evmosd start"
    networks:
      - chains
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.evmos-stripprefix.stripprefix.prefixes=/evmos"
      - "traefik.http.services.evmos.loadbalancer.server.port=8545"
      - "traefik.http.routers.evmos.entrypoints=websecure"
      - "traefik.http.routers.evmos.tls.certresolver=myresolver"
      - "traefik.http.routers.evmos.rule=Host(`$DOMAIN`) && PathPrefix(`/evmos`)"
      - "traefik.http.routers.evmos.middlewares=evmos-stripprefix, ipwhitelist"

volumes:
    evmos_data:  