version: "3.1"
services:
  fantom-archive:
    build:
      args:
        VERSION: release/txtracing/1.1.2-rc.5
      context: ./fantom
      dockerfile: Dockerfile
    environment:
      - SNAPSHOT_URL_DISABLED=https://download.fantom.network/opera_5may22.tgz
    volumes:
      - "fantom:/datadir"
    expose:
      - "18545"
    networks:
      - chains
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.fantom-archive-stripprefix.stripprefix.prefixes=/fantom-archive"
      - "traefik.http.services.fantom-archive.loadbalancer.server.port=18545"
      - "traefik.http.routers.fantom-archive.entrypoints=websecure"
      - "traefik.http.routers.fantom-archive.tls.certresolver=myresolver"
      - "traefik.http.routers.fantom-archive.rule=Host(`$DOMAIN`) && PathPrefix(`/fantom-archive`)"
      - "traefik.http.routers.fantom-archive.middlewares=fantom-archive-stripprefix, ipwhitelist"

volumes:
  fantom-archive:
