version: "3.1"
services:
  fantom-proxy:
    image: stakesquid/eth-cluster
    environment:
      - FULLNODE_WS_URL=${FANTOM_FULLNODE_WS}
      - FULLNODE_RPC_URL=${FANTOM_FULLNODE_RPC}
      - ARCHIVE_RPC_URL=${FANTOM_ARCHIVE_RPC}      
    expose:
      - "8545"
    networks:
      - chains
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.fantom-stripprefix.stripprefix.prefixes=$FANTOM_PREFIX"
      - "traefik.http.services.fantom.loadbalancer.server.port=8545"
      - "traefik.http.routers.fantom.entrypoints=websecure"
      - "traefik.http.routers.fantom.tls.certresolver=myresolver"
      - "traefik.http.routers.fantom.rule=Host(`$FANTOM_DOMAIN`) && PathPrefix(`$FANTOM_PREFIX`)"
      - "traefik.http.routers.fantom.middlewares=fantom-stripprefix, ipwhitelist"
