version: '3.1'

services:
  ftp:
    image: garethflowers/ftp-server
    restart: unless-stopped
    volumes:
      - /backup:/home/${FTP_USER}
    environment:
      - FTP_PASS=${FTP_PASS}
      - FTP_USER=${FTP_USER}
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp'      



      
