version: '3.1'

services:
  fuse-nethermind:
    image: fusenet/node:nethermind-1.17.3-v4.0.0
    expose:
      - "30300/tcp"
      - "30300/udp"
      - "8545"
      - "8546"
    command: "--config fuse --Init.WebSocketsEnabled true --HealthChecks.Enabled true --HealthChecks.Slug /api/health --JsonRpc.EnabledModules Eth,Web3,RPC,Net,Parity,Health"
    volumes:
      - fuse-nethermind-keystore:/nethermind/keystore
      - fuse-nethermind-logs:/nethermind/logs
      - fuse-nethermind-db:/nethermind/nethermind_db
    networks:
      - chains
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.fuse-stripprefix.stripprefix.prefixes=/fuse"
      - "traefik.http.services.fuse.loadbalancer.server.port=8545"
      - "traefik.http.routers.fuse.entrypoints=websecure"
      - "traefik.http.routers.fuse.tls.certresolver=myresolver"
      - "traefik.http.routers.fuse.rule=Host(`$DOMAIN`) && PathPrefix(`/fuse`)"
      - "traefik.http.routers.fuse.middlewares=fuse-stripprefix, ipwhitelist"
      - "prometheus-scrape.enabled=true"
      - "prometheus-scrape.port=3000"
      - "prometheus-scrape.job_name=fuse-nethermind"

volumes:
    fuse-nethermind-keystore:
    fuse-nethermind-logs:
    fuse-nethermind-db:
