version: '3.1'

services:
  haqq:                         
    image: alhaqq/haqq:v1.7.4
    expose: 
      # HTTP server / GraphQL API 
      - 8545
    ports:
      - "55774:55774"
    user: root
    command: haqqd start --p2p.laddr "tcp://0.0.0.0:55774" --rpc.laddr "tcp://0.0.0.0:26657"
    networks:                            
      - chains                                                                                        
    volumes:                                                                                          
      - "haqq:/root/.haqqd"
      - ".jwtsecret:/jwtsecret"
    restart: unless-stopped
    stop_grace_period: 1m
    labels:                     
      - "traefik.enable=true"
      - "traefik.http.middlewares.haqq-stripprefix.stripprefix.prefixes=/haqq"                  
      - "traefik.http.services.haqq.loadbalancer.server.port=26657"                                 
      - "traefik.http.routers.haqq.entrypoints=websecure"                                          
      - "traefik.http.routers.haqq.tls.certresolver=myresolver"                                    
      - "traefik.http.routers.haqq.rule=Host(`$DOMAIN`) && PathPrefix(`/haqq`)"                 
      - "traefik.http.routers.haqq.middlewares=haqq-stripprefix, ipwhitelist"
      - "prometheus-scrape.enabled=true"
      - "prometheus-scrape.port=6060"
      - "prometheus-scrape.job_name=haqq"
      - "prometheus-scrape.metrics_path=/debug/metrics/prometheus"

volumes:
  haqq:
