version: '3.1'

services:
  haqq:                         
    image: alhaqq/haqq:v1.7.4
    expose: 
      # HTTP server / GraphQL API 
      - 8545                   
    ports:                      
      - "29568:29568"                                                                                 
      - "29568:29568/udp"
    user: root
    command:
      [                                                                                               
        # Blockchain sync mode ("snap", "full" or "light")                                            
        "--syncmode=snap",
        "--port=29568",
        # Megabytes of memory allocated to internal caching                                           
        "--cache=8192",
        # Enable the WS-RPC server         
        "--ws",
        "--ws.port=8545",
        "--ws.addr=0.0.0.0",
        # Enable the HTTP-RPC server      
        "--http",
        "--http.port=8545",
        "--http.addr=0.0.0.0",                     
        "--http.vhosts=*",                         
        # Enable GraphQL on the HTTP-RPC server. Note that GraphQL can only be started if an HTTP server is started as well.                                                                               
        "--graphql",                               
        "--graphql.vhosts=*",             
        # Enable metrics collection and reporting                                                     
        "--metrics",
        "--metrics.addr=0.0.0.0",
        # Ethereum holesky
        "--holesky",                                                                                  
        # Maximum number of network peers (network disabled if set to 0) (default: 50)                
        "--maxpeers=30",
        # The Merge
        "--authrpc.jwtsecret=/jwtsecret",
        "--authrpc.addr=0.0.0.0",
        "--authrpc.vhosts=*"
      ]                                                                                               
    networks:                            
      - chains                                                                                        
    volumes:                                                                                          
      - "haqq:/home/root/.haqqd"
      - ".jwtsecret:/jwtsecret"
    restart: unless-stopped
    stop_grace_period: 1m
    labels:                     
      - "traefik.enable=true"
      - "traefik.http.middlewares.holesky-stripprefix.stripprefix.prefixes=/holesky"                  
      - "traefik.http.services.holesky.loadbalancer.server.port=8545"                                 
      - "traefik.http.routers.holesky.entrypoints=websecure"                                          
      - "traefik.http.routers.holesky.tls.certresolver=myresolver"                                    
      - "traefik.http.routers.holesky.rule=Host(`$DOMAIN`) && PathPrefix(`/holesky`)"                 
      - "traefik.http.routers.holesky.middlewares=holesky-stripprefix, ipwhitelist"
      - "prometheus-scrape.enabled=true"
      - "prometheus-scrape.port=6060"
      - "prometheus-scrape.job_name=haqq"
      - "prometheus-scrape.metrics_path=/debug/metrics/prometheus"

volumes:
  haqq:
