version: '3.1'

services:
  erigon-holesky-fullnode:
    image: thorax/erigon:v2.57.3
    expose:
      - "23769"
      - "54112"
      - "9090"
      - "8545"
      - "8551"
    ports:
      - "23769:23769"
      - "23769:23769/udp"
      - "54112:54112"
      - "54112:54112/udp"
    volumes:
      - erigon-holesky-fullnode:/home/erigon/.local/share/erigon
      - .jwtsecret:/jwtsecret
    networks:
      - chains
    command: >
      --chain holesky
      --internalcl
      --prune.h.older=128
      --prune.r.older=128
      --prune.t.older=128
      --prune.c.older=128
      --port=23769
      --torrent.port=54112
      --metrics --metrics.addr=0.0.0.0 --metrics.port=6060
      --private.api.addr=0.0.0.0:9090
      --torrent.upload.rate="1250mb"
      --torrent.download.rate="1250mb"
      --nat=stun
      --downloader.verify
      --pprof
      --pprof.addr=0.0.0.0
      --pprof.port=6061
      --authrpc.addr=0.0.0.0
      --authrpc.vhosts=*
      --authrpc.jwtsecret=/jwtsecret
      --http.addr=0.0.0.0
      --http.vhosts=*
      --http.corsdomain=*
      --http.api=eth,erigon,web3,net,debug,trace,txpool
      --rpc.returndata.limit=1000000
      --rpc.gascap=5000000000
      --ws 
    restart: unless-stopped
    stop_grace_period: 1m
    labels:
      - "prometheus-scrape.enabled=true"
      - "prometheus-scrape.port=6060"
      - "prometheus-scrape.job_name=erigon"
      - "prometheus-scrape.metrics_path=/debug/metrics/prometheus"
      - "traefik.enable=true"
      - "traefik.http.middlewares.erigon-holesky-fullnode-stripprefix.stripprefix.prefixes=/holesky-fullnode"
      - "traefik.http.services.erigon-holesky-fullnode.loadbalancer.server.port=8545"
      - "traefik.http.routers.erigon-holesky-fullnode.entrypoints=websecure"
      - "traefik.http.routers.erigon-holesky-fullnode.tls.certresolver=myresolver"
      - "traefik.http.routers.erigon-holesky-fullnode.rule=Host(`$DOMAIN`) && PathPrefix(`/holesky-fullnode`)"
      - "traefik.http.routers.erigon-holesky-fullnode.middlewares=erigon-holesky-fullnode-stripprefix, ipwhitelist"
      
volumes:
    erigon-holesky-fullnode:
