version: "3.1"
services:
  mainnet-proxy:
    image: stakesquid/eth-cluster@sha256:537f9207d3894732c946244b464c4482fb0661f2b3ac1daffb1f549a64a49d79
    environment:
      - FULLNODE_WS_URL=${MAINNET_PREFIX_FULLNODE_WS}
      - FULLNODE_RPC_URL=${MAINNET_PREFIX_FULLNODE_RPC}
      - ARCHIVE_RPC_URL=${MAINNET_PREFIX_ARCHIVE_RPC}
      - ALL_TRACE_TO_ARCHIVE=${MAINNET_PREFIX_TRACE_TO_ARCHIVE:-true}
    expose:
      - "8545"
    networks:
      - chains
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.mainnet-proxy-stripprefix.stripprefix.prefixes=$MAINNET_PREFIX_PREFIX"
      - "traefik.http.services.mainnet-proxy.loadbalancer.server.port=8545"
      - "traefik.http.routers.mainnet-proxy.entrypoints=websecure"
      - "traefik.http.routers.mainnet-proxy.tls.certresolver=myresolver"
      - "traefik.http.routers.mainnet-proxy.rule=Host(`$MAINNET_PREFIX_DOMAIN`) && PathPrefix(`$MAINNET_PREFIX_PREFIX`)"
      - "traefik.http.routers.mainnet-proxy.middlewares=mainnet-proxy-stripprefix, ipwhitelist"
