version: '3.1'

services:
  nethermind-mainnet:
    image: nethermind/nethermind:latest
    restart: always
    stop_grace_period: 1m
    command: |
      --JsonRpc.Enabled=true
      --JsonRpc.JwtSecretFile=/jwt.hex
      --Metrics.Enabled=true
    ports:
      - '34896:34896/tcp' # p2p
      - '34896:34896/udp' # p2p
    networks:
      - chains
    volumes:
      - nethermind_mainnet_db:/nethermind/nethermind_db
      - nethermind_mainnet_keystore:/nethermind/keystore
      - nethermind_mainnet_logs:/nethermind/logs
      - .jwtsecret:/jwt.hex
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NETHERMIND_CONFIG=mainnet
      - NETHERMIND_JSONRPCCONFIG_ENGINEENABLEDMODULES=[Eth,AccountAbstraction,Subscribe,TxPool,Web3,Personal,Proof,Net,Parity,Health]
      - NETHERMIND_JSONRPCCONFIG_ENGINEHOST=0.0.0.0
      - NETHERMIND_JSONRPCCONFIG_ENGINEPORT=8551
      - NETHERMIND_JSONRPCCONFIG_HOST=0.0.0.0
      - NETHERMIND_METRICSCONFIG_EXPOSEPORT=9091
      - NETHERMIND_NETWORKCONFIG_P2PPORT=34896
      - NETHERMIND_NETWORKCONFIG_DISCOVERYPORT=34896
      - NETHERMIND_NETWORKCONFIG_MAXACTIVEPEERS=250
      - NETHERMIND_SYNCCONFIG_FASTSYNC=true
      - NETHERMIND_SYNCCONFIG_SNAPSYNC=true
      - NETHERMIND_SYNCCONFIG_FASTBLOCKS=true
      - NETHERMIND_SYNCCONFIG_DOWNLOADBODIESINFASTSYNC=true
      - NETHERMIND_SYNCCONFIG_DOWNLOADRECEIPTSINFASTSYNC=true
      - NETHERMIND_SYNCCONFIG_ANCIENTBODIESBARRIER=1
      - NETHERMIND_SYNCCONFIG_ANCIENTRECEIPTSBARRIER=1
    logging:
      options:
        max-size: "1000m"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.nethermind-mainnet-stripprefix.stripprefix.prefixes=/nethermind-mainnet"
      - "traefik.http.services.nethermind-mainnet.loadbalancer.server.port=8545"
      - "traefik.http.routers.nethermind-mainnet.entrypoints=websecure"
      - "traefik.http.routers.nethermind-mainnet.tls.certresolver=myresolver"
      - "traefik.http.routers.nethermind-mainnet.rule=Host(`$DOMAIN`) && PathPrefix(`/nethermind-mainnet`)"
      - "traefik.http.routers.nethermind-mainnet.middlewares=nethermind-mainnet-stripprefix, ipwhitelist"
      - "prometheus-scrape.enabled=true"
      - "prometheus-scrape.port=9091"
      - "prometheus-scrape.job_name=nethermind-mainnet"
      
      

  lighthouse-mainnet:
    image: sigp/lighthouse:latest-modern
    restart: unless-stopped
    networks:
      - chains
    ports:
      - 20506:20506/tcp # p2p
      - 20506:20506/udp # p2p
    expose:
      - 5054 # metrics
      - 4000 # http
      - 20506 # p2p
    volumes:
      - mainnet_consensus:/data
      - .jwtsecret:/jwt.hex
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: |
      lighthouse
      beacon_node
      --network=mainnet
      --disable-upnp
      --datadir=/data
      --port=20506
      --http
      --http-address=0.0.0.0
      --http-port=4000
      --target-peers=50
      --execution-endpoint=http://nethermind-mainnet:8551
      --execution-jwt=/jwt.hex
      --debug-level=info
      --validator-monitor-auto
      --subscribe-all-subnets
      --import-all-attestations
      --metrics
      --metrics-port=5054
      --metrics-address=0.0.0.0
      --checkpoint-sync-url=https://mainnet-checkpoint-sync.attestant.io
    labels:
      - "prometheus-scrape.enabled=true"
      - "prometheus-scrape.port=5054"
      - "prometheus-scrape.job_name=lighthouse-mainnet"
      - "prometheus-scrape.metrics_path=/metrics"
      - "traefik.enable=true"
      - "traefik.http.middlewares.lighthouse-mainnet-stripprefix.stripprefix.prefixes=/lighthouse-mainnet"
      - "traefik.http.services.lighthouse-mainnet.loadbalancer.server.port=4000"
      - "traefik.http.routers.lighthouse-mainnet.entrypoints=websecure"
      - "traefik.http.routers.lighthouse-mainnet.tls.certresolver=myresolver"
      - "traefik.http.routers.lighthouse-mainnet.rule=Host(`$DOMAIN`) && PathPrefix(`/lighthouse-mainnet`)"
      - "traefik.http.routers.lighthouse-mainnet.middlewares=lighthouse-mainnet-stripprefix, ipwhitelist"


volumes:
  nethermind_mainnet_db:
  nethermind_mainnet_keystore:
  nethermind_mainnet_logs:
  mainnet_consensus:
