version: '3.1'

services:
  nethermind-mainnet:
    image: nethermind/nethermind:1.25.4
    restart: always
    stop_grace_period: 1m
    command: |
      --JsonRpc.Enabled=true
      --JsonRpc.JwtSecretFile=/jwt.hex
      --Metrics.Enabled=true
      --TraceStore.Enabled=true
      --TraceStore.BlocksToKeep=0
      --TraceStore.TraceTypes=Trace,Rewards
      --Sync.FastSync=false
    ports:
      - '34896:34896/tcp' # p2p
      - '34896:34896/udp' # p2p
    networks:
      - chains
    volumes:
      - nethermind_mainnet_db:/nethermind/nethermind_db
      - nethermind_mainnet_keystore:/nethermind/keystore
      - nethermind_mainnet_logs:/nethermind/logs
      - .jwtsecret:/jwt.hex
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NETHERMIND_CONFIG=mainnet
      - NETHERMIND_JSONRPCCONFIG_ENGINEENABLEDMODULES=[Eth,AccountAbstraction,Subscribe,TxPool,Web3,Personal,Proof,Net,Parity,Health,Trace]
      - NETHERMIND_JSONRPCCONFIG_ENGINEHOST=0.0.0.0
      - NETHERMIND_JSONRPCCONFIG_ENGINEPORT=8551
      - NETHERMIND_JSONRPCCONFIG_HOST=0.0.0.0
      - NETHERMIND_METRICSCONFIG_EXPOSEPORT=9091
      - NETHERMIND_NETWORKCONFIG_P2PPORT=34896
      - NETHERMIND_NETWORKCONFIG_DISCOVERYPORT=34896
      - NETHERMIND_NETWORKCONFIG_MAXACTIVEPEERS=250
      - NETHERMIND_PRUNINGCONFIG_CACHEMB=4096
      - NETHERMIND_PRUNINGCONFIG_FULLPRUNINGMAXDEGREEOFPARALLELISM=0
      - NETHERMIND_PRUNINGCONFIG_FULLPRUNINGTHRESHOLDMB=96000
      - NETHERMIND_RECEIPTCONFIG_STORERECEIPTS=false
      - NETHERMIND_RECEIPTCONFIG_TXLOOKUPLIMIT=128
      - NETHERMIND_RECEIPTCONFIG_RECEIPTSMIGRATION=true
      - NETHERMIND_SYNCCONFIG_FASTSYNC=true
      - NETHERMIND_SYNCCONFIG_SNAPSYNC=true
      - NETHERMIND_SYNCCONFIG_FASTBLOCKS=true
      - NETHERMIND_SYNCCONFIG_NONVALIDATORNODE=true
      - NETHERMIND_SYNCCONFIG_DOWNLOADBODIESINFASTSYNC=false
      - NETHERMIND_SYNCCONFIG_DOWNLOADHEADERSINFASTSYNC=false
      - NETHERMIND_SYNCCONFIG_DOWNLOADRECEIPTSINFASTSYNC=false
      - NETHERMIND_SYNCCONFIG_ANCIENTBODIESBARRIER=1
      - NETHERMIND_SYNCCONFIG_ANCIENTRECEIPTSBARRIER=1
    logging:
      options:
        max-size: "1000m"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.nethermind-mainnet-stripprefix.stripprefix.prefixes=/nethermind-mainnet"
      - "traefik.http.services.nethermind-mainnet.loadbalancer.server.port=8545"
      - "traefik.http.routers.nethermind-mainnet.entrypoints=websecure"
      - "traefik.http.routers.nethermind-mainnet.tls.certresolver=myresolver"
      - "traefik.http.routers.nethermind-mainnet.rule=Host(`$DOMAIN`) && PathPrefix(`/nethermind-mainnet`)"
      - "traefik.http.routers.nethermind-mainnet.middlewares=nethermind-mainnet-stripprefix, ipwhitelist"
      - "prometheus-scrape.enabled=true"
      - "prometheus-scrape.port=9091"
      - "prometheus-scrape.job_name=nethermind-mainnet"

      
  nimbus-mainnet:
    build:
      context: ./nimbus
      args:
        UPSTREAM_VERSION: v24.3.0
    restart: unless-stopped
    stop_grace_period: 1m
    environment:
      NETWORK: mainnet
      LOG_TYPE: INFO
      P2P_TCP_PORT: 23079
      P2P_UDP_PORT: 23079
      CHECKPOINT_SYNC_URL: "https://mainnet-checkpoint-sync.attestant.io"
      EXTRA_OPTS: ""
      FEE_RECIPIENT_ADDRESS: ""
      EXECUTION_ENDPOINT: "http://nethermind-mainnet:8551"
    volumes:
      - nimbus-mainnet:/home/user/nimbus-eth2/build/data
      - .jwtsecret:/jwt.hex      
    networks:
      - chains
    ports:
      - 23079:23079/tcp # p2p
      - 23079:23079/udp # p2p
    expose:
      - 8008 # metrics
      - 4500 # http
      - 23079 # p2p
    labels:
      - "prometheus-scrape.enabled=true"
      - "prometheus-scrape.port=8008"
      - "prometheus-scrape.job_name=nimbus-mainnet"
      - "prometheus-scrape.metrics_path=/metrics"
      - "traefik.enable=true"
      - "traefik.http.middlewares.nimbus-mainnet-stripprefix.stripprefix.prefixes=/nimbus-mainnet"
      - "traefik.http.services.nimbus-mainnet.loadbalancer.server.port=4500"
      - "traefik.http.routers.nimbus-mainnet.entrypoints=websecure"
      - "traefik.http.routers.nimbus-mainnet.tls.certresolver=myresolver"
      - "traefik.http.routers.nimbus-mainnet.rule=Host(`$DOMAIN`) && PathPrefix(`/nimbus-mainnet`)"
      - "traefik.http.routers.nimbus-mainnet.middlewares=nimbus-mainnet-stripprefix, ipwhitelist"


volumes:
  nethermind_mainnet_db:
  nethermind_mainnet_keystore:
  nethermind_mainnet_logs:
  nimbus-mainnet:
