version: '3.1'                              
                                                   
services:                             
                                                   
  nethermind-gnosis-chiado:        
    image: nethermind/nethermind:1.27.0
    user: root
    volumes:                  
      - "gnosis-chiado-nethermind-fullnode:/data"
      - .jwtsecret:/jwtsecret
    expose:  
      - "7806"
      - "9090"
      - "8545"               
      - "8551"               
    ports: 
      - "7806:7806" 
      - "7806:7806/udp"
    restart: unless-stopped
    environment:
      #- "NETHERMIND_SYNCCONFIG_NONVALIDATORNODE=true"
      ##- "NETHERMIND_SYNCCONFIG_PIVOTHASH=0x4d2eedcf61a0b19ca46b6f944e732ef6baef71b9e879912a6ae122a7c4c2bd17"
      ##- "NETHERMIND_SYNCCONFIG_PIVOTNUMBER=32299602"
      - "NETHERMIND_SYNCCONFIG_FASTSYNC=true"
      #- "NETHERMIND_SYNCCONFIG_DOWNLOADRECEIPTSINFASTSYNC=false"
      #- "NETHERMIND_SYNCCONFIG_DOWNLOADBODIESINFASTSYNC=false"
      #- "NETHERMIND_SYNCCONFIG_DOWNLOADHEADERSINFASTSYNC=false"
    command: |
      --config=chiado
      --datadir=/data
      --log=INFO
      --JsonRpc.Enabled=true
      --JsonRpc.Host=0.0.0.0
      --JsonRpc.Port=8545
      --JsonRpc.EnabledModules=[Web3,Eth,Subscribe,Net]
      --JsonRpc.JwtSecretFile=/jwtsecret
      --JsonRpc.EngineHost=0.0.0.0
      --JsonRpc.EnginePort=8551
      --Network.DiscoveryPort=7806
      --HealthChecks.Enabled=false
      --Pruning.CacheMb=2048
    stop_grace_period: 3m                         
    labels:                                      
      - "prometheus-scrape.enabled=true"
      - "prometheus-scrape.port=6060"                                                                 
      - "prometheus-scrape.job_name=nethermind"                                                           
      - "prometheus-scrape.metrics_path=/debug/metrics/prometheus"
      - "traefik.enable=true"                                                                         
      - "traefik.http.middlewares.nethermind-gnosis-chiado-stripprefix.stripprefix.prefixes=/gnosis-chiado"
      - "traefik.http.services.nethermind-gnosis-chiado.loadbalancer.server.port=8545"                    
      - "traefik.http.routers.nethermind-gnosis-chiado.entrypoints=websecure"
      - "traefik.http.routers.nethermind-gnosis-chiado.tls.certresolver=myresolver"
      - "traefik.http.routers.nethermind-gnosis-chiado.rule=Host(`$DOMAIN`) && PathPrefix(`/gnosis-chiado`)"
      - "traefik.http.routers.nethermind-gnosis-chiado.middlewares=nethermind-gnosis-chiado-stripprefix, ipwhitelist"
    networks:   
      - chains        
    logging:
      options:
        max-file: '1'
        compress: 'false'
      driver: local

      
  nimbus-gnosis-chiado:
    build:
      context: ./gnosis/nimbus
    restart: unless-stopped
    stop_grace_period: 1m
    user: root
    volumes:
      - nimbus-gnosis-chiado:/data
      - .jwtsecret:/jwt:ro
    environment:
      CHECKPOINT_SYNC_URL: "https://checkpoint.chiadochain.net/"
    command: |
        --data-dir=/data
        --web3-url=http://nethermind-gnosis-chiado:8551
        --jwt-secret=/jwt
        --light-client-data-serve=true
        --light-client-data-import-mode=full
        --tcp-port=61460
        --udp-port=61460
        --rest
        --rest-address=0.0.0.0
        --network=chiado
        --history=prune
    networks:
      - chains
    ports:
      - 61460:61460/tcp # p2p
      - 61460:61460/udp # p2p
    expose:
      - 8008 # metrics
      - 4500 # http
      - 61460 # p2p
    labels:
      - "prometheus-scrape.enabled=true"
      - "prometheus-scrape.port=8008"
      - "prometheus-scrape.job_name=nimbus-gnosis-chiado"
      - "prometheus-scrape.metrics_path=/metrics"
      - "traefik.enable=true"
      - "traefik.http.middlewares.nimbus-gnosis-chiado-stripprefix.stripprefix.prefixes=/nimbus-gnosis-chiado"
      - "traefik.http.services.nimbus-gnosis-chiado.loadbalancer.server.port=4500"
      - "traefik.http.routers.nimbus-gnosis-chiado.entrypoints=websecure"
      - "traefik.http.routers.nimbus-gnosis-chiado.tls.certresolver=myresolver"
      - "traefik.http.routers.nimbus-gnosis-chiado.rule=Host(`$DOMAIN`) && PathPrefix(`/nimbus-gnosis-chiado`)"
      - "traefik.http.routers.nimbus-gnosis-chiado.middlewares=nimbus-gnosis-chiado-stripprefix, ipwhitelist"

      
volumes:
  gnosis-chiado-nethermind-fullnode:
  nimbus-gnosis-chiado:    
