version: '3.1'

services:
  op-lisk-sepolia: # this is Optimism's geth client
    #image: stakesquid/op-lisk-sepolia:v0.1
    build:
      context: ./op
      dockerfile: Dockerfile.debug
      args:
        OP_GETH_VERSION: v1.101315.2
        OP_NODE_VERSION: v1.7.7
    expose:
      - 8545       # RPC / Websocket      
      - 54521     # P2P TCP (currently unused)
      - 54521/udp # P2P UDP (currently unused)
      - 6060       # metrics
    ports:
      - "54521:54521"
      - "54521:54521/udp"
    #command: [ "sh", "./geth-entrypoint" ]
    entrypoint: ./geth
    command: --datadir=/data --rollup.sequencerhttp=https://rpc.sepolia-api.lisk.com --verbosity=3 --http --http.corsdomain=* --http.vhosts=* --http.addr=0.0.0.0 --http.port=8545 --http.api=web3,debug,eth,net,engine --authrpc.addr=0.0.0.0 --authrpc.port=8551 --authrpc.vhosts=* --authrpc.jwtsecret=/jwtsecret --ws --ws.addr=0.0.0.0 --ws.port=8545 --ws.origins=* --ws.api=debug,eth,net,engine --bootnodes=enr:-Iu4QI5BdaTmfMhNKXd-vSniNRSCXk-a3m3nQbe9TCV3puGtCr6FvX6-Vr0Uvx4tYVilGCIYdQNf6fK8O2MKxVqjYJ8BgmlkgnY0gmlwhCKN6PiJc2VjcDI1NmsxoQLBQIaRwlvNxrRKcGtxKmh4JS_orkawS44D4KIORICoi4N0Y3CCIyuDdWRwgiMr --override.fjord=1716998400 --override.ecotone=1708534800 --override.canyon=0 --maxpeers=0
    restart: always
    stop_grace_period: 3m    
    volumes:
      - lisk-sepolia:/data
      - .jwtsecret:/jwtsecret
    environment:
      - "OP_GETH_GENESIS_FILE_PATH=/app/sepolia/lisk/genesis.json"
      - "OP_GETH_SEQUENCER_HTTP=https://rpc.sepolia-api.lisk.com"
      - "OP_GETH_BOOTNODES=enr:-Iu4QI5BdaTmfMhNKXd-vSniNRSCXk-a3m3nQbe9TCV3puGtCr6FvX6-Vr0Uvx4tYVilGCIYdQNf6fK8O2MKxVqjYJ8BgmlkgnY0gmlwhCKN6PiJc2VjcDI1NmsxoQLBQIaRwlvNxrRKcGtxKmh4JS_orkawS44D4KIORICoi4N0Y3CCIy\
uDdWRwgiMr"
      - "OP_GETH_GCMODE=full"
      - "OP_GETH_STATE_SCHEME=hash"
      - "GETH_DB_ENGINE=pebble"
      - "P2P_PORT=54521"
      - "WS_PORT=8545"
      - "OP_NODE_L2_ENGINE_AUTH_RAW=${JWTSECRET}"
      - "OP_NODE_L2_ENGINE_AUTH=/jwtsecret"
    labels:                     
      - "traefik.enable=true"
      - "traefik.http.middlewares.base-stripprefix.stripprefix.prefixes=/lisk-sepolia"                      
      - "traefik.http.services.base.loadbalancer.server.port=8545"
      - "traefik.http.routers.base.entrypoints=websecure"                                              
      - "traefik.http.routers.base.tls.certresolver=myresolver"                                        
      - "traefik.http.routers.base.rule=Host(`$DOMAIN`) && PathPrefix(`/lisk-sepolia`)"                     
      - "traefik.http.routers.base.middlewares=base-stripprefix, ipwhitelist"                           
    networks:                                                                                         
      - chains
            
volumes:  
    lisk-sepolia:
