version: '3.1'

services:
  op-lisk-mainnet: # this is Optimism's geth client
    #image: stakesquid/op-lisk-sepolia:v0.1
    build: ./op
    expose:
      - 8545       # RPC / Websocket      
      - 6999     # P2P TCP (currently unused)
      - 6999/udp # P2P UDP (currently unused)
      - 6060       # metrics
    ports:
      - "6999:6999"
      - "6999:6999/udp"
    command: [ "sh", "./geth-entrypoint" ]
    #entrypoint: ./geth
    #command: --datadir=/data --rollup.sequencerhttp=https://rpc.api.lisk.com --verbosity=3 --http --http.corsdomain=* --http.vhosts=* --http.addr=0.0.0.0 --http.port=8545 --http.api=web3,debug,eth,net,engine --authrpc.addr=0.0.0.0 --authrpc.port=8551 --authrpc.vhosts=* --authrpc.jwtsecret=/jwtsecret --ws --ws.addr=0.0.0.0 --ws.port=8545 --ws.origins=* --ws.api=debug,eth,net,engine
    restart: always
    stop_grace_period: 3m    
    volumes:
      - lisk-mainnet:/data
      - .jwtsecret:/jwtsecret
    environment:
      - "OP_GETH_GENESIS_FILE_PATH=/app/mainnet/lisk/genesis.json"
      - "OP_GETH_SEQUENCER_HTTP=https://rpc.api.lisk.com"
      - "OP_GETH_GCMODE=full"
      - "OP_GETH_STATE_SCHEME=hash"
      - "GETH_DB_ENGINE=pebble"
      - "P2P_PORT=6999"
      - "WS_PORT=8545"
      - "OP_NODE_L2_ENGINE_AUTH_RAW=${JWTSECRET}"
      - "OP_NODE_L2_ENGINE_AUTH=/jwtsecret"
    labels:                     
      - "traefik.enable=true"
      - "traefik.http.middlewares.base-stripprefix.stripprefix.prefixes=/lisk-mainnet"                      
      - "traefik.http.services.base.loadbalancer.server.port=8545"
      - "traefik.http.routers.base.entrypoints=websecure"                                              
      - "traefik.http.routers.base.tls.certresolver=myresolver"                                        
      - "traefik.http.routers.base.rule=Host(`$DOMAIN`) && PathPrefix(`/lisk-mainnet`)"                     
      - "traefik.http.routers.base.middlewares=base-stripprefix, ipwhitelist"                           
    networks:                                                                                         
      - chains

      
  op-lisk-mainnet-node:
    #image: stakesquid/op-lisk-mainnet:v0.1
    build: ./op
    depends_on:
      - op-lisk-mainnet
    expose:
      - 8545     # RPC
      - 3074     # P2P TCP
      - 3074/udp # P2P UDP
      - 7300     # metrics
      - 6060     # pprof
    ports:
      - "3074:3074"
      - "3074:3074/udp"
    command: [ "sh", "./op-node-entrypoint" ]
    restart: always
    volumes:
      - .jwtsecret:/jwtsecret
      - ./op/mainnet/lisk/rollup.json:/app/mainnet/lisk/rollup.json
    stop_grace_period: 30s
    environment:
      #- "OP_NODE_NETWORK=lisk-mainnet"
      - "OP_NODE_L1_ETH_RPC=${LISK_MAINNET_L1_ENDPOINT}"
      #- "OP_NODE_L2_ENGINE_AUTH_RAW=688f5d737bad920bdfb2fc2f488d6b6209eebda1dae949a8de91398d932c517a"
      - "OP_NODE_L2_ENGINE_AUTH_RAW=${JWTSECRET}"
      - "OP_NODE_L2_ENGINE_AUTH=/jwtsecret"
      - "OP_NODE_L2_ENGINE_RPC=http://op-lisk-mainnet:8551"
      - "OP_NODE_LOG_LEVEL=info"
      - "OP_NODE_METRICS_ADDR=0.0.0.0"
      - "OP_NODE_METRICS_ENABLED=true"
      - "OP_NODE_METRICS_PORT=7300"
      - "OP_NODE_P2P_AGENT=lisk"
      - "OP_NODE_P2P_LISTEN_IP=0.0.0.0"
      - "OP_NODE_P2P_LISTEN_TCP_PORT=3074"
      - "OP_NODE_P2P_LISTEN_UDP_PORT=3074"
      - "OP_NODE_ROLLUP_CONFIG=/app/mainnet/lisk/rollup.json"
      - "OP_NODE_RPC_ADDR=0.0.0.0"
      - "OP_NODE_P2P_ADVERTISE_IP=${IP}"
      - "OP_NODE_RPC_PORT=8545"
      - "OP_NODE_SNAPSHOT_LOG=/tmp/op-node-snapshot-log"
      - "OP_NODE_VERIFIER_L1_CONFS=4"
      - "OP_NODE_L1_RPC_MAX_BATCH_SIZE=${LISK_MAINNET_L1_BATCH_SIZE:-20}"
      - "OP_NODE_L1_RPC_RATE_LIMIT=${LISK_MAINNET_L1_RATE_LIMIT:-30}"
      - "OP_NODE_L1_RPC_KIND=${LISK_MAINNET_L1_ENDPOINT_KIND:-basic}"
      - "OP_NODE_L1_TRUST_RPC=${LISK_MAINNET_L1_ENDPOINT_TRUST:-false}"
      - "OP_NODE_L1_BEACON=${LISK_MAINNET_L1_BEACON_URL}"
    networks:                                                                                         
      - chains
      
volumes:  
    lisk-mainnet:
