version: '3.1'

services:
  op-zora-archive: 
    build:
      context: ./op
      dockerfile: Dockerfile.debug
      args:
        OP_GETH_VERSION: v1.101315.2
        OP_NODE_VERSION: v1.7.7
    expose:
      - 8545       # RPC / Websocket      
      - 18322     # P2P TCP (currently unused)
      - 18322/udp # P2P UDP (currently unused)
      - 6060       # metrics
    ports:
      - "18322:18322"
      - "18322:18322/udp"
    command: [ "sh", "./geth-entrypoint" ]
    restart: always
    stop_grace_period: 3m    
    volumes:
      - zora-archive:/data
      - .jwtsecret:/jwtsecret
    environment:
      - "GETH_GENESIS_FILE_PATH=/app/mainnet/zora/genesis.json"
      - "GETH_ROLLUP_SEQUENCERHTTP=https://rpc-zora-mainnet-0.t.conduit.xyz"
      - "GETH_GCMODE=archive"
      - "GETH_NODISCOVER=true"
      - "GETH_STATE_SCHEME=hash"
      - "GETH_DB_ENGINE=leveldb"
      - "IP=${IP}"
      - "P2P_PORT=18322"
      - "WS_PORT=8545"
      - "OP_NODE_L2_ENGINE_AUTH=/jwtsecret"
      - "HOST_IP=${IP}"
      - "GETH_OVERRIDE_CANYON=1704992401"
      - "GETH_OVERRIDE_DELTA=1708560000"
      - "GETH_OVERRIDE_ECOTONE=1710374401"
      - "GETH_OVERRIDE_FJORD=1720627201"
    labels:                     
      - "traefik.enable=true"
      - "traefik.http.middlewares.zora-stripprefix.stripprefix.prefixes=/zora-archive"                      
      - "traefik.http.services.zora.loadbalancer.server.port=8545"
      - "traefik.http.routers.zora.entrypoints=websecure"                                              
      - "traefik.http.routers.zora.tls.certresolver=myresolver"                                        
      - "traefik.http.routers.zora.rule=Host(`$DOMAIN`) && PathPrefix(`/zora-archive`)"                     
      - "traefik.http.routers.zora.middlewares=zora-stripprefix, ipwhitelist"                           
    networks:                                                                                         
      - chains
      
volumes:  
    zora-archive:
