version: '3.1'

services:
  optimism-dtl:
    image: ethereumoptimism/data-transport-layer:${IMAGE_TAG__DTL:-latest}
    restart: unless-stopped
    user: root
    entrypoint:
      - /bin/sh
      - -c
      - "/scripts/dtl-start.sh"
    env_file:
      - ./optimism/env/dtl.env
      - .env
    volumes:
      - optimism-dtl:/db
      - ./optimism/scripts/:/scripts/
    environment:
      - "SYNC_SOURCE=l1"
      - "DATA_TRANSPORT_LAYER__RPC_ENDPOINT=${OPTIMISM_L1_URL}"
    networks:                                                                                         
      - chains

  optimism-l2geth:
    image: ethereumoptimism/l2geth:${IMAGE_TAG__L2GETH:-latest}
    restart: unless-stopped
    stop_grace_period: 3m
    user: root
    entrypoint:
      - /bin/sh
      - -c
      - "/scripts/l2geth-init.sh && /scripts/l2geth-start.sh"
    env_file:
      - ./optimism/env/l2geth.env
      - .env
    volumes:
      - optimism-geth:/geth
      - ./optimism/scripts/:/scripts/
    expose:
      - 9991 # http
      - 9992 # ws
    environment:
      - "NODE_TYPE=archive"
      - "SYNC_SOURCE=l1"
    networks:                                                                                         
      - chains

volumes:
  optimism-dtl:
  optimism-geth:  
