version: '3.1'

services:

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    ports:
      - "443:443"
      - "127.0.0.1:8080:8080"
    expose:
      - "8082"
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.metrics.address=:8082"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # TESTING
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=$MAIL"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "./traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"

### POKT
  pocket-lt-1:
    build: pokt
    ports:
      - "127.0.0.1:8081:8081"
      - "26656:26656"
    expose:
      - 26656
      - 26660
      - 8081
      - 8083
    #command: pocket start --simulateRelay
    environment:
      - POCKET_CORE_KEY=$POKT_LT_1_POCKET_CORE_KEY
      - POCKET_CORE_PASSPHRASE=$POKT_LT_1_POCKET_CORE_PASSPHRASE
      - POCKET_SNAPSHOT=$POCKET_SNAPSHOT
    volumes:
      - pocket-lt-1:/home/app/.pocket/data
      - pocket-lt-1-addrbook:/home/app/.pocket/addrbook
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.pocket-lt-1.loadbalancer.server.port=8081"
      - "traefik.http.routers.pocket-lt-1.entrypoints=websecure"
      - "traefik.http.routers.pocket-lt-1.tls.certresolver=myresolver"
      - "traefik.http.routers.pocket-lt-1.rule=Host(`$POKT_LT_1_DOMAIN`) && Path(`/v1`, `/v1/client/{dispatch|relay|challenge|sim}`)"
      - "prometheus-scrape.enabled=true"
      - "prometheus-scrape.port=8083"
      - "prometheus-scrape.job_name=pocket-lt-1"


  pocket-lt-2:
    build: pokt
    ports:
      - "127.0.0.1:8082:8081"
      - "26657:26656"
    expose:
      - 26656
      - 26660
      - 8081
      - 8083
    #command: pocket start --simulateRelay
    environment:
      - POCKET_CORE_KEY=$POKT_LT_2_POCKET_CORE_KEY
      - POCKET_CORE_PASSPHRASE=$POKT_LT_2_POCKET_CORE_PASSPHRASE
      - POCKET_SNAPSHOT=$POCKET_SNAPSHOT
    volumes:
      - pocket-lt-2:/home/app/.pocket/data
      - pocket-lt-2-addrbook:/home/app/.pocket/addrbook
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.pocket-lt-2.loadbalancer.server.port=8081"
      - "traefik.http.routers.pocket-lt-2.entrypoints=websecure"
      - "traefik.http.routers.pocket-lt-2.tls.certresolver=myresolver"
      - "traefik.http.routers.pocket-lt-2.rule=Host(`$POKT_LT_2_DOMAIN`) && Path(`/v1`, `/v1/client/{dispatch|relay|challenge|sim}`)"
      - "prometheus-scrape.enabled=true"
      - "prometheus-scrape.port=8083"
      - "prometheus-scrape.job_name=pocket-lt-2"

#  pocket-lt-3:
#    build: pokt
#    ports:
#      - "127.0.0.1:8082:8081"
#      - "26657:26656"
#    expose:
#      - 26656
#      - 26660
#      - 8081
#      - 8083
#    #command: pocket start --simulateRelay
#    environment:
#      - POCKET_CORE_KEY=$POKT_LT_3_POCKET_CORE_KEY
#      - POCKET_CORE_PASSPHRASE=$POKT_LT_3_POCKET_CORE_PASSPHRASE
#      - POCKET_SNAPSHOT=$POCKET_SNAPSHOT
#    volumes:
#      - pocket-lt-3:/home/app/.pocket/data
#      - pocket-lt-3-addrbook:/home/app/.pocket/addrbook
#    restart: unless-stopped
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.services.pocket-lt-3.loadbalancer.server.port=8081"
#      - "traefik.http.routers.pocket-lt-3.entrypoints=websecure"
#      - "traefik.http.routers.pocket-lt-3.tls.certresolver=myresolver"
#      - "traefik.http.routers.pocket-lt-3.rule=Host(`$POKT_LT_3_DOMAIN`) && Path(`/v1`, `/v1/client/{dispatch|relay|challenge|sim}`)"
#      - "prometheus-scrape.enabled=true"
#      - "prometheus-scrape.port=8083"
#      - "prometheus-scrape.job_name=pocket-lt-3"

  haproxy:
    build: haproxy
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    expose:
      - "8404"
      - "80"
    ports:
      - "127.0.0.1:80:80"
    restart: always
    labels:
      - "prometheus-scrape.enabled=true"
      - "prometheus-scrape.port=8404"
      - "prometheus-scrape.job_name=haproxy"
      - "prometheus-scrape.metrics_path=/metrics"

### VOLUMES
volumes:
  pocket-lt-1:
  pocket-lt-1-addrbook:
  pocket-lt-2:
  pocket-lt-2-addrbook:
  pocket-lt-3:
  pocket-lt-3-addrbook: