version: '3.1'

services:
  bor:
    image: 0xpolygon/bor:1.2.8
    sysctls:
      net.ipv4.tcp_slow_start_after_idle: 0
      net.ipv4.tcp_no_metrics_save: 1
    volumes:                  
      - "bor_data:/datadir"
    expose:
      - 8545
    ports:                   
      - "40303:40303"                                                                                 
      - "40303:40303/udp"                
      command: server --bor.heimdall=https://polygon-heimdall-rest.publicnode.com --port=40303 --http --http.port=8545 --http.vhosts=* --ws --ws.port=8545 --ws.origins=* --ws.addr=0.0.0.0 --http.addr=0.0.0.0 --datadir=/datadir --rpc.returndatalimit=1000000
    restart: unless-stopped                 
    labels:                     
      - "traefik.enable=true"
      - "traefik.http.middlewares.bor-stripprefix.stripprefix.prefixes=/polygon"                      
      - "traefik.http.services.bor.loadbalancer.server.port=8545"                                     
      - "traefik.http.routers.bor.entrypoints=websecure"                                              
      - "traefik.http.routers.bor.tls.certresolver=myresolver"                                        
      - "traefik.http.routers.bor.rule=Host(`$DOMAIN`) && PathPrefix(`/polygon`)"                     
      - "traefik.http.routers.bor.middlewares=bor-stripprefix, ipwhitelist"                           
    networks:                                                                                         
      - chains

volumes:  
    bor_data:
