version: '3.1'

services:
  polygon-amoy-erigon-archive:
    image: thorax/erigon:${ERIGON_VERSION:-v2.59.0}
    user: root
    stop_grace_period: 3m
    volumes:
      - "polygon-amoy-erigon-archive:/datadir"
      - "/slowdisk:/slowdisk"
    expose:
      - 29877
      - 49749
      - 8545
    ports:
      - "30248:30248"
      - "30248:30248/udp"
      - "32011:32011"
      - "32011:32011/udp"
    restart: unless-stopped
    command: --chain=amoy --db.pagesize=16k --bor.heimdall=https://heimdall-api-amoy.polygon.technology --http --http.addr=0.0.0.0 --http.port=8545 --http.compression --http.vhosts='*' --http.corsdomain='*' --http.api=eth,debug,net,web3,erigon,bor --ws --ws.compression --rpc.gascap=300000000 --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --bodies.cache=5G --rpc.batch.limit=200000 --batchSize=2048MB --port=49749 --p2p.protocol=66 --datadir=/datadir --ethash.dagdir=/datadir/ethash --rpc.returndata.limit=1100000 --db.size.limit 7697000000000 --torrent.port=29877 --nat=stun

    stop_grace_period: 1m
    labels:
      - "prometheus-scrape.enabled=true"
      - "prometheus-scrape.port=6060"
      - "prometheus-scrape.job_name=erigon"
      - "prometheus-scrape.metrics_path=/debug/metrics/prometheus"
      - "traefik.enable=true"
      - "traefik.http.middlewares.polygon-amoy-erigon-archive-stripprefix.stripprefix.prefixes=/polygon-amoy-archive"
      - "traefik.http.services.polygon-amoy-erigon-archive.loadbalancer.server.port=8545"
      - "traefik.http.routers.polygon-amoy-erigon-archive.entrypoints=websecure"
      - "traefik.http.routers.polygon-amoy-erigon-archive.tls.certresolver=myresolver"
      - "traefik.http.routers.polygon-amoy-erigon-archive.rule=Host(`$DOMAIN`) && PathPrefix(`/polygon-amoy-archive`)"
      - "traefik.http.routers.polygon-amoy-erigon-archive.middlewares=polygon-amoy-erigon-archive-stripprefix, ipwhitelist"
    networks:
      - chains

volumes:
    polygon-amoy-erigon-archive:
