version: '3.1'

services:
  bor:                      
    build:                                
      args:                
        UPSTREAM_VERSION: v0.2.14
      context: ./polygon/bor                       
      dockerfile: Dockerfile
    sysctls:
      net.ipv4.tcp_slow_start_after_idle: 0
      net.ipv4.tcp_no_metrics_save: 1
    environment:
      - SNAPSHOT_URL=https://matic-blockchain-snapshots.s3-accelerate.amazonaws.com/matic-mainnet/bor-fullnode-snapshot-2022-02-20.tar.gz
      - BOOTSTRAP=1
      - ARCHIVE=0                                                                              
    volumes:                  
      - "bor_data:/datadir"
    ports:                   
      - "40303:40303"                                                                                 
      - "40303:40303/udp"                
    depends_on:                                                                                       
      - heimdallr                                                                                     
    restart: unless-stopped                 
    labels:                     
      - "traefik.enable=true"
      - "traefik.http.middlewares.bor-stripprefix.stripprefix.prefixes=/polygon"                      
      - "traefik.http.services.bor.loadbalancer.server.port=8545"                                     
      - "traefik.http.routers.bor.entrypoints=websecure"                                              
      - "traefik.http.routers.bor.tls.certresolver=myresolver"                                        
      - "traefik.http.routers.bor.rule=Host(`$DOMAIN`) && PathPrefix(`/polygon`)"                     
      - "traefik.http.routers.bor.middlewares=bor-stripprefix, ipwhitelist"                           
    networks:                                                                                         
      - chains

volumes:  
    bor_data: