version: '3.1'

services:
  prysm:
    image: prysmaticlabs/prysm-beacon-chain:stable
    ports:
      - "127.0.0.1:3500:3500"
      - "13000:13000"
      - "12000:12000/udp"
    command:
      [                                                                                               
        "--datadir=/data",
        "--jwt-secret=/jwtsecret",
        "--rpc-host=0.0.0.0",
        "--grpc-gateway-host=0.0.0.0",
        "--monitoring-host=0.0.0.0",
        "--execution-endpoint=http://$EXECUTION_CLIENT:8551",
        "--accept-terms-of-use"
      ]                                                                                               
    networks:                            
      - chains                                                                                        
    volumes:                                                                                          
      - "prysm_data:/data"
      - ".jwtsecret:/jwtsecret"
    restart: unless-stopped
    stop_grace_period: 1m

volumes:
    prysm_data: