version: '3.1'

services:
  rootstock-mainnet:                         
    image: rsksmart/rskj:IRIS-3.3.0
    expose: 
      # HTTP server / GraphQL API 
      - 4444                   
    ports:                      
      - "5050:5050"                                                                                 
      - "5050:5050/udp"  
    networks:                            
      - chains                                                                                        
    volumes:                                                                                          
      - "rootstock-mainnet:/var/lib/rsk/.rsk"
    restart: unless-stopped
    stop_grace_period: 5m
    labels:                     
      - "traefik.enable=true"
      - "traefik.http.middlewares.rootstock-mainnet-stripprefix.stripprefix.prefixes=/rootstock-mainnet"                  
      - "traefik.http.services.rootstock-mainnet.loadbalancer.server.port=4444"                                 
      - "traefik.http.routers.rootstock-mainnet.entrypoints=websecure"                                          
      - "traefik.http.routers.rootstock-mainnet.tls.certresolver=myresolver"                                    
      - "traefik.http.routers.rootstock-mainnet.rule=Host(`$DOMAIN`) && PathPrefix(`/rootstock-mainnet`)"                 
      - "traefik.http.routers.rootstock-mainnet.middlewares=rootstock-mainnet-stripprefix, ipwhitelist"
    
volumes:
  rootstock-mainnet:
