version: '3.1'

services:
  erigon-sepolia-fullnode:
    image: thorax/erigon:v2.57.3
    expose:
      - "23932"
      - "34975"
      - "9090"
      - "8545"
      - "8551"
    ports:
      - "23932:23932"
      - "23932:23932/udp"
      - "34975:34975"
      - "34975:34975/udp"
    volumes:
      - erigon-sepolia-fullnode:/home/erigon/.local/share/erigon
      - .jwtsecret:/jwtsecret
    networks:
      - chains
    command: >
      --chain sepolia
      --internalcl
      --prune.h.older=128
      --prune.r.older=128
      --prune.t.older=128
      --prune.c.older=128
      --port=23932
      --torrent.port=34975
      --metrics --metrics.addr=0.0.0.0 --metrics.port=6060
      --private.api.addr=0.0.0.0:9090
      --torrent.upload.rate="1250mb"
      --torrent.download.rate="1250mb"
      --nat=stun
      --downloader.verify
      --pprof
      --pprof.addr=0.0.0.0
      --pprof.port=6061
      --authrpc.addr=0.0.0.0
      --authrpc.vhosts=*
      --authrpc.jwtsecret=/jwtsecret
      --http.addr=0.0.0.0
      --http.vhosts=*
      --http.corsdomain=*
      --http.api=eth,erigon,web3,net,debug,trace,txpool
      --rpc.returndata.limit=1000000
      --rpc.gascap=5000000000
      --ws 
    restart: unless-stopped
    stop_grace_period: 1m
    labels:
      - "prometheus-scrape.enabled=true"
      - "prometheus-scrape.port=6060"
      - "prometheus-scrape.job_name=erigon"
      - "prometheus-scrape.metrics_path=/debug/metrics/prometheus"
      - "traefik.enable=true"
      - "traefik.http.middlewares.erigon-sepolia-fullnode-stripprefix.stripprefix.prefixes=/sepolia-fullnode"
      - "traefik.http.services.erigon-sepolia-fullnode.loadbalancer.server.port=8545"
      - "traefik.http.routers.erigon-sepolia-fullnode.entrypoints=websecure"
      - "traefik.http.routers.erigon-sepolia-fullnode.tls.certresolver=myresolver"
      - "traefik.http.routers.erigon-sepolia-fullnode.rule=Host(`$DOMAIN`) && PathPrefix(`/sepolia-fullnode`)"
      - "traefik.http.routers.erigon-sepolia-fullnode.middlewares=erigon-sepolia-fullnode-stripprefix, ipwhitelist"
      
volumes:
    erigon-sepolia-fullnode:
