services:
  taiko-hekla:
    image: us-docker.pkg.dev/evmchain/images/taiko-geth:latest
    restart: unless-stopped
    pull_policy: always
    stop_grace_period: 3m
    volumes:
      - taiko:/data/taiko-geth
    expose:
      - 6060
      - 8545
      - 8551
    ports:
      - "52158:52158"
      - "52158:52158/udp"
    command: |
      --taiko
      --networkid 167009
      --gcmode full
      --datadir /data/taiko-geth
      --metrics
      --metrics.addr "0.0.0.0"
      --bootnodes "enode://2f7ee605f84362671e7d7c6d47b69a3358b0d87e9ba4648befcae8b19453275ed19059db347c459384c1a3e5486419233c06bf6c4c6f489d81ace6f301a2a446@43.153.55.134:30303,enode://c067356146268d2855ad356c1ce36ba9f78c1633a72f9b7f686679c2ffe04bab6d24e48ef6eefb0e01aa00dff5024f7f94bc583da90b6027f40be4129bbbc5fd@43.153.90.191:30303,enode://acc2bdb6416feddff9734bee1e6de91e684e9df5aeb1d36698cc78b920600aed36a2871e4ad0cf4521afcdc2cde8e2cd410a57038767c356d4ce6c69b9107a5a@170.106.109.12:30303,enode://eb5079aae185d5d8afa01bfd2d349da5b476609aced2b57c90142556cf0ee4a152bcdd724627a7de97adfc2a68af5742a8f58781366e6a857d4bde98de6fe986@34.66.210.65:30303,enode://2294f526cbb7faa778192289c252307420532191438ce821d3c50232e019a797bda8c8f8541de0847e953bb03096123856935e32294de9814d15d120131499ba@34.72.186.213:30303"
      --authrpc.addr "0.0.0.0"
      --authrpc.vhosts "*"
      --http
      --http.api admin,debug,eth,net,web3,txpool,taiko
      --http.addr "0.0.0.0"
      --http.vhosts "*"
      --ws
      --ws.api debug,eth,net,web3,txpool,taiko
      --ws.addr "0.0.0.0"
      --ws.port 8545
      --ws.origins "*"
      --gpo.defaultprice "10000000"
      --port 52158
      --discovery.port 52158
      --maxpeers 50
      --maxpendpeers 0
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.taiko-hekla-stripprefix.stripprefix.prefixes=/taiko-hekla"
      - "traefik.http.services.taiko-hekla.loadbalancer.server.port=8545"
      - "traefik.http.routers.taiko-hekla.entrypoints=websecure"
      - "traefik.http.routers.taiko-hekla.tls.certresolver=myresolver"
      - "traefik.http.routers.taiko-hekla.rule=Host(`$DOMAIN`) && PathPrefix(`/taiko-hekla`)"
      - "traefik.http.routers.taiko-hekla.middlewares=taiko-hekla-stripprefix, ipwhitelist"
    networks:
      - chains

  taiko-hekla-client-driver:
    image: us-docker.pkg.dev/evmchain/images/taiko-client:latest
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - taiko
    environment:
      - "TAIKO_L1_ADDRESS=0x79C9109b764609df928d16fC4a91e9081F7e87DB"
      - "TAIKO_TOKEN_L1_ADDRESS=0x6490E12d480549D333499236fF2Ba6676C296011"
      - "ASSIGNMENT_HOOK_L1_ADDRESS=0x9e640a6aadf4f664CF467B795c31332f44AcBe6c"
      - "TAIKO_L2_ADDRESS=0x1670090000000000000000000000000000010001"
      - "L1_ENDPOINT_HTTP=${TAIKO_HOLESKY_EXECUTION_RPC}"
      - "L1_ENDPOINT_WS=${TAIKO_HOLESKY_EXECUTION_WS}"
      - "L1_BEACON_HTTP=${TAIKO_HOLESKY_BEACON_REST}"
      - "L2_CHECKPOINT_SYNC_RPC=https://rpc.hekla.taiko.xyz"
    volumes:
      - taiko:/data/taiko-geth
      - ./taiko/script:/script
    entrypoint:
      - /bin/sh
      - -c
      - "/script/start-driver.sh"
    networks:
      - chains
      
volumes:
  taiko:
