version: '3.1'
    
services:
  tz3iTQcdoV6V:
    image: sha256:70ce58cae12f
    restart: unless-stopped
    expose:
      - 6700
      - 7300
    command: /config/tz3iTQcdoV6V.json
    volumes:
      - "./main_configs:/config"      
    networks:
      - chains
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.tz3iTQcdoV6V.loadbalancer.server.port=6700"
      - "traefik.http.routers.tz3iTQcdoV6V.entrypoints=websecure"
      - "traefik.http.routers.tz3iTQcdoV6V.tls.options=/main_configs/tz3iTQcdoV6V.crt,/main_configs/tz3iTQcdoV6V.key"
      - "traefik.http.routers.tz3iTQcdoV6V.rule=Host(`index.8ch2.com`) && PathPrefix(`/`)"

