version: '3.1'

# Client https://github.com/NethermindEth/nethermind
# Nethermind container as in https://github.com/gnosischain/documentation/blob/a46e0964c7e4f75bed0ff02f7ae157c4417f60bd/docs/node/execution-layer-validator.md#setup-as-archive-node
# Beaconchain container as in https://github.com/gnosischain/lighthouse-launch

services:
  xdai-archive:
    hostname: xdai-archive
    container_name: xdai-archive
    image: nethermindeth/nethermind:trace-db
    restart: always
    stop_grace_period: 1m
    command: |
      --JsonRpc.Enabled=true
      --JsonRpc.Host=0.0.0.0
      --JsonRpc.JwtSecretFile=/jwt.hex
      --JsonRpc.EngineHost=0.0.0.0
      --JsonRpc.EnginePort=8551
      --Metrics.Enabled=true
      --TraceStore.Enabled=true
      --TraceStore.BlocksToKeep=0
      --TraceStore.TraceTypes=Trace,Rewards
    ports:
      - '30303:30303/tcp' # p2p
      - '30303:30303/udp' # p2p
      - '127.0.0.1:8545:8545'
      - '127.0.0.1:9091:9091'
    networks:
      - chains
    volumes:
      - nethermind_db:/nethermind/nethermind_db
      - nethermind_keystore:/nethermind/keystore
      - nethermind_logs:/nethermind/logs
      - .jwtsecret:/jwt.hex
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NETHERMIND_CONFIG=xdai_archive
      - NETHERMIND_JSONRPCCONFIG_ENGINEENABLEDMODULES=[Eth,AccountAbstraction,Subscribe,TxPool,Web3,Personal,Proof,Net,Parity,Health,Trace]
      - NETHERMIND_METRICSCONFIG_EXPOSEPORT=9091
      - NETHERMIND_NETWORKCONFIG_MAXACTIVEPEERS=150
    logging:
      options:
        max-size: "1000m"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.xdai-archive-stripprefix.stripprefix.prefixes=/xdai-archive"
      - "traefik.http.services.xdai-archive.loadbalancer.server.port=8545"
      - "traefik.http.routers.xdai-archive.entrypoints=websecure"
      - "traefik.http.routers.xdai-archive.tls.certresolver=myresolver"
      - "traefik.http.routers.xdai-archive.rule=Host(`$DOMAIN`) && PathPrefix(`/xdai-archive`)"
      - "traefik.http.routers.xdai-archive.middlewares=xdai-archive-stripprefix, ipwhitelist"

  xdai_consensus:
    container_name: xdai_consensus
    image: sigp/lighthouse:latest-modern
    restart: unless-stopped
    networks:
      - chains
    ports:
      - 9001:9001/tcp # p2p
      - 9001:9001/udp # p2p
    expose:
      - 5054 # metrics
      - 4000 # http
    volumes:
      - xdai_consensus:/data
      - .jwtsecret:/jwt.hex
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: |
      lighthouse
      beacon_node
      --network=gnosis
      --disable-upnp
      --datadir=/data
      --port=9001
      --http
      --http-address=0.0.0.0
      --http-port=4000
      --target-peers=50
      --execution-endpoint=http://xdai-archive:8551
      --execution-jwt=/jwt.hex
      --debug-level=info
      --validator-monitor-auto
      --subscribe-all-subnets
      --import-all-attestations
      --metrics
      --metrics-port=5054
      --metrics-address=0.0.0.0
      --checkpoint-sync-url=https://checkpoint.gnosischain.com/

volumes:
  nethermind_db:
  nethermind_keystore:
  nethermind_logs:
  xdai_consensus:
